-- 두 과목 이상을 수강한 학생들의 학번, 이름, 과목명, 점수 출력

SELECT * FROM STUDENT;
SELECT * FROM ENROL;
SELECT * FROM SUBJECT;

SELECT S.STU_NO, STU_NAME, SUB_NAME, ENR_GRADE
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
INNER JOIN SUBJECT SUB ON SUB.SUB_NO = E.SUB_NO
INNER JOIN (
    SELECT COUNT(*) AS CNT, STU_NO
    FROM ENROL
    GROUP BY STU_NO
) T ON T.STU_NO = S.STU_NO
WHERE CNT >= 2;

