SELECT ROWNUM, EMPNO, ENAME
FROM (
    SELECT
        EMPNO, ENAME
    FROM EMP
    ORDER BY ENAME
) WHERE ROWNUM <= 5;

SELECT *
FROM (
    SELECT ROWNUM AS NUM, EMPNO, ENAME
    FROM EMP
)
WHERE NUM = 5;

SELECT ROWNUM, EMPNO, ENAME
FROM EMP;

SELECT DNAME, ROUND(AVG(SAL),1)
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME;

SELECT *
FROM (
    SELECT DNAME, ROUND(AVG(SAL),1) AS AVG_SAL
    FROM EMP E
    INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY DNAME
    ORDER BY AVG_SAL DESC
) WHERE ROWNUM = 1;
