-- STUDENT
-- 평균점수가 가장 낮은 학과의 학과명, 평균 점수 출력

SELECT * FROM ENROL;

SELECT *
FROM STUDENT S;

SELECT *
FROM (
SELECT AVG(ENR_GRADE) AS AVG_ENR, STU_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT
ORDER BY AVG_ENR ASC
) WHERE ROWNUM = 1;

SELECT AVG(ENR_GRADE), STU_DEPT
FROM STUDENT S
INNER JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY STU_DEPT;

