-- UNION
SELECT EMPNO, ENAME, SAL
FROM EMP WHERE COMM IS NOT NULL
UNION ALL
SELECT EMPNO, ENAME, SAL
FROM EMP WHERE SAL > 2000;


SELECT ROUND(AVG(STU_HEIGHT), 2)
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT AVG(STU_HEIGHT)
FROM STUDENT;


SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),2) AS 평균키
FROM STUDENT
GROUP BY STU_DEPT
UNION
SELECT
'전체평균', AVG(STU_HEIGHT) AS 평균키
FROM STUDENT;


SELECT STU_DEPT, 평균키
FROM (
    SELECT STU_DEPT, ROUND(AVG(STU_HEIGHT),2) AS 평균키,
    1 AS ORDERKEY
    FROM STUDENT
    GROUP BY STU_DEPT
    UNION
    SELECT '전체평균', AVG(STU_HEIGHT) AS 평균키,
    2 AS ORDERKEY
    FROM STUDENT
) ORDER BY ORDERKEY;

SELECT * FROM EMP;
SELECT * FROM DEPT;

SELECT DNAME AS 부서명, ROUND(AVG(SAL),2) AS 급여평균
FROM EMP E
INNER JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY DNAME
UNION
SELECT '합계', AVG(SAL)
FROM EMP E;


