SELECT *
FROM STUDENT;

SELECT S1.STU_NAME, S1.STU_DEPT, S1.STU_WEIGHT, COUNT(S2.STU_WEIGHT) AS 몸무게큰사람
FROM STUDENT S1
LEFT JOIN STUDENT S2 ON S1.STU_WEIGHT < S2.STU_WEIGHT
GROUP BY S1.STU_NAME, S1.STU_DEPT, S1.STU_WEIGHT
ORDER BY STU_WEIGHT;