-- PROCEDURE
-- 선언부 (DECLARE)
-- 예외처리(EXCEPTION)
-- 실행부

CREATE OR REPLACE PROCEDURE TEST_PRO1 
(P_EMPNO IN NUMBER) 
IS 
BEGIN 
    UPDATE EMP
    SET SAL = SAL + 100
    WHERE EMPNO = P_EMPNO;
    COMMIT;
END TEST_PRO1;
/

EXECUTE TEST_PRO1(7000);

SELECT *
FROM EMP;

-- STUDENT
-- 학번을 받아서 해당 학생의 키를 1 증가시키는 프로시저 생성

SELECT *
FROM STUDENT;

CREATE OR REPLACE PROCEDURE UPDATE_HEIGHT
(P_STUNO IN STUDENT.STU_NO%TYPE)
IS
BEGIN
    UPDATE STUDENT
    SET STU_HEIGHT = STU_HEIGHT + 1
    WHERE STU_NO = P_STUNO;
    COMMIT;
END UPDATE_HEIGHT;
/

EXECUTE UPDATE_HEIGHT(20153075);



--IF

CREATE OR REPLACE PROCEDURE SEARCH_DEPT
(P_EMPNO IN EMP.EMPNO%TYPE)
IS
V_DEPTNO EMP.DEPTNO%TYPE;
BEGIN
    DBMS_OUTPUT.ENABLE;
    
    SELECT DEPTNO
    INTO V_DEPTNO
    FROM EMP
    WHERE EMPNO = P_EMPNO;
    IF V_DEPTNO = 10 THEN 
        DBMS_OUTPUT.PUT_LINE('10번 부서 사람입니다.');
    ELSIF V_DEPTNO = 20 THEN
        DBMS_OUTPUT.PUT_LINE('20번 부서 사람입니다.');
    ELSIF V_DEPTNO = 30 THEN
        DBMS_OUTPUT.PUT_LINE('30번 부서 사람입니다.');
    ELSE
        DBMS_OUTPUT.PUT_LINE('해당없음');
    END IF;
    
END SEARCH_DEPT;
/

SET SERVEROUTPUT ON;

EXECUTE SEARCH_DEPT(7369);
