SELECT D2.DNAME, AVG(S.HEIGHT)
FROM STU S
INNER JOIN DEPARTMENT D1 ON S.DEPTNO1 = D1.DEPTNO
INNER JOIN DEPARTMENT D2 ON D1.PART = D2.DEPTNO
GROUP BY D2.DNAME;

SELECT *
FROM DEPARTMENT;

SELECT AVG(STU.HEIGHT)
FROM STU;

SELECT STU_NAME, NVL(TO_CHAR(ENR_GRADE), '점수없음') AS 시험점수
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO;

SELECT *
FROM ENROL;

SELECT S.NAME, D1.DNAME AS 전공, NVL(D2.DNAME, '부전공 없음') AS 부전공
FROM STU S
LEFT JOIN DEPARTMENT D1 ON D1.DEPTNO = S.DEPTNO1
LEFT JOIN DEPARTMENT D2 ON D2.DEPTNO = S.DEPTNO2;

SELECT *
FROM DEPARTMENT;

SELECT E1.EMPNO, E1.ENAME, NVL(E2.ENAME,'팀장없음') AS 팀장이름
FROM EMP E1
LEFT JOIN EMP E2 ON E1.MGR = E2.EMPNO;

SELECT STU_NAME, COUNT(ENR_GRADE) AS 시험응시수
FROM STUDENT S
LEFT JOIN ENROL E ON S.STU_NO = E.STU_NO
GROUP BY S.STU_NAME
ORDER BY 시험응시수 DESC;

SELECT * 
FROM BOARD
;

INSERT INTO BOARD
VALUES (
BOARD_SEQ.NEXTVAL, '시퀀스테스트2', '시퀀스2~~', 'USER02', 1, 1, 1, 1, 'N', SYSDATE, SYSDATE
);

CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 21
MINVALUE 1
MAXVALUE 9999
NOCYCLE;

SELECT TEST_SEQ.NEXTVAL
FROM DUAL;