CREATE OR REPLACE FUNCTION DATE_FORMAT
(
    I_EMPNO IN EMP.EMPNO%TYPE
)
    RETURN CHAR
IS
    V_HIREDATE VARCHAR(10);
BEGIN
    SELECT TO_CHAR(HIREDATE, 'YYYY-MM-DD')
    INTO V_HIREDATE
    FROM EMP
    WHERE EMPNO = I_EMPNO;

    RETURN V_HIREDATE;
END;
/

SELECT EMPNO, ENAME, DATE_FORMAT(EMPNO)
FROM EMP;

SELECT *
FROM EMP;

CREATE OR REPLACE FUNCTION DATE_FORMAT2
(
    I_DATE IN DATE
)
    RETURN VARCHAR2
IS
    V_DATE VARCHAR2(100);
BEGIN
--    SELECT TO_CHAR(I_DATE, 'YYYY-MM-DD')
--    INTO V_DATE
--    FROM DUAL;
--    RETURN V_DATE;
    RETURN TO_CHAR(I_DATE, 'YYYY-MM-DD');
END DATE_FORMAT2;
/

SELECT DATE_FORMAT2(HIREDATE)
FROM EMP;

SELECT DATE_FORMAT2(HIREDATE)
FROM PROFESSOR;

SELECT DATE_FORMAT2(BIRTHDAY)
FROM STU;

CREATE OR REPLACE FUNCTION DATE_FORMAT3
(
    I_DATE IN DATE,
    I_FORMAT IN NUMBER
)
    RETURN VARCHAR2
IS
    V_HIREDATE VARCHAR2(100);
BEGIN
    IF I_FORMAT = 1 THEN
        V_HIREDATE := TO_CHAR(I_DATE, 'YYYY-MM-DD');
    ELSIF I_FORMAT = 2 THEN
        V_HIREDATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH:MI:SS');
    ELSIF I_FORMAT = 3 THEN
        V_HIREDATE := TO_CHAR(I_DATE, 'YYYY-MM-DD HH24:MI:SS');
    ELSE
        V_HIREDATE := '데이터 잘못 넣으셨음';
    END IF;
    
    RETURN V_HIREDATE;
    
END DATE_FORMAT3;
/

SELECT DATE_FORMAT3(HIREDATE, 1)
FROM EMP;

