SELECT JUMIN_FORMAT(JUMIN, 1)
FROM STU;

SELECT JUMIN_FORMAT(JUMIN, 2)
FROM STU;

CREATE OR REPLACE FUNCTION JUMIN_FORMAT
(
    I_JUMIN IN VARCHAR2,
    I_FORMAT IN NUMBER
)
    RETURN VARCHAR2
IS
    V_CHAR VARCHAR2(100);
BEGIN
    IF I_FORMAT = 1 THEN
        V_CHAR := SUBSTR(I_JUMIN, 1, 6) || '-' || SUBSTR(I_JUMIN, 7);
    ELSIF I_FORMAT = 2 THEN
        V_CHAR := SUBSTR(I_JUMIN, 1, 6) || '-' || SUBSTR(I_JUMIN, 7, 1) || '******';
    ELSE
        V_CHAR := '데이터 입력 오류';
    END IF;
    
    RETURN V_CHAR;
    
END JUMIN_FORMAT;
/
    
