-- 아래 프로시저를 실행 시 EMP 테이블에 데이터 삽입

CREATE OR REPLACE PROCEDURE EMP_INSERT
(
    P_EMPNO IN EMP.EMPNO%TYPE, 
    P_ENAME IN EMP.ENAME%TYPE, 
    P_DEPTNO IN EMP.DEPTNO%TYPE
)
IS
BEGIN
    INSERT INTO EMP (EMPNO, ENAME, HIREDATE, DEPTNO) VALUES
    (P_EMPNO, P_ENAME, SYSDATE, P_DEPTNO);
    COMMIT;
    
END EMP_INSERT;
/

EXECUTE EMP_INSERT(1234, 'HONG', 20);

SELECT *
FROM EMP
WHERE ENAME = 'HONG';