CREATE TABLE EMP_LOG(
    L_EMPNO NUMBER,
    L_MGR NUMBER,
    L_SAL NUMBER,
    L_COMM NUMBER,
    L_ID VARCHAR2(30),
    L_DATE DATE,
    EVENT VARCHAR2(20)
);

COMMIT;

CREATE OR REPLACE TRIGGER EMP_TRIGGER1
    AFTER
    INSERT OR DELETE OR UPDATE ON EMP
    FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO EMP_LOG
        VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE, 'I');
    ELSIF DELETING THEN
        INSERT INTO EMP_LOG
        VALUES (:OLD.EMPNO, :OLD.MGR, :OLD.SAL, :OLD.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE, 'D');
    ELSIF UPDATING THEN
        INSERT INTO EMP_LOG
        VALUES (:NEW.EMPNO, :NEW.MGR, :NEW.SAL, :NEW.COMM, SYS_CONTEXT('USERENV', 'SESSION_USER'), SYSDATE, 'U');
    END IF;
    
END;
/

INSERT INTO EMP(EMPNO, ENAME, MGR, SAL, COMM)
VALUES ('1357', 'PARK', '7521', 2000, 100);

SELECT * FROM EMP;

SELECT *
FROM EMP_LOG;

UPDATE EMP
SET SAL = 3000
WHERE EMPNO = 1357;

DELETE FROM EMP
WHERE EMPNO = 1357;
COMMIT;

